spring:
  datasource:
    url: ${database.dev.url}
    username: ${database.dev.username}
    password: ${database.dev.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  devtools:
    restart:
      enabled: false


giljabi:
  mountain100:  #산림청 100대 명산 gpx, 오래된것 같음, 화악산에서 gpx 없었으면 ....
    path: x:/home/ubuntu/apps/giljabi/data/forest100/ # --> ${minio.bucketData}/forest100
  xmlshare: #gpx, tcx 공유파일 경로, 삭제하지 않는 파일, 블로그에 공유된 파일
    path: x:/home/ubuntu/apps/giljabi/data/share/     # --> ${minio.bucketData}/share
  gpx:  # 사용자가 작성한 파일은 모두 공유하게 변경
    path: x:/home/ubuntu/apps/giljabi/data/gpx # --> ${minio.bucketService}/gpx

##### 파일은 public만 사용함...private은 사용안함--> 관리가 귀찮네...
##### s3사용하지 않고 로컬에 저장하게 변경
#minio:
#  url: ${bucket.url}
##  bucketPrivate: gil-media-pri #public gpx, elevation, gpximages 서비스에서 사용하는 데이터, 사용자가 생성한 파일들
##  bucketPublicUrl: http://localhost:9000
#  bucketPublicUrl: ${bucket.media-public.url}
#  bucketPublic: ${bucket.media-public.name} #public /forest100, /share
#  accessKey: ${bucket.accessKey}
#  secretKey: ${bucket.secretKey}


